/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pares_vista_control.gerente;

import java.util.List;
import java.util.Vector;
import javax.swing.JList;

/**
 *
 * @author g01
 */
public class ConsultarVehiculosVista extends javax.swing.JFrame {
    private final CtrlVistaConsultarVehiculos controlador;

    
    public ConsultarVehiculosVista() {
        initComponents();
        controlador = new CtrlVistaConsultarVehiculos(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelSuperior = new javax.swing.JPanel();
        botonVerVehiculos = new javax.swing.JButton();
        scrollListaVehiculos = new javax.swing.JScrollPane();
        listaVehiculos = new javax.swing.JList<String>();
        PanelInferior = new javax.swing.JPanel();
        botonCerrarSesion = new javax.swing.JButton();
        scrollDetallesPunto = new javax.swing.JScrollPane();
        detallesPunto = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(2, 1));

        PanelSuperior.setLayout(new java.awt.GridLayout(1, 2));

        botonVerVehiculos.setText("Ver vehículos del punto situados fuera");
        botonVerVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerVehiculosActionPerformed(evt);
            }
        });
        PanelSuperior.add(botonVerVehiculos);

        listaVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaVehiculosMouseClicked(evt);
            }
        });
        listaVehiculos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaVehiculosValueChanged(evt);
            }
        });
        scrollListaVehiculos.setViewportView(listaVehiculos);

        PanelSuperior.add(scrollListaVehiculos);

        getContentPane().add(PanelSuperior);

        PanelInferior.setLayout(new java.awt.GridLayout(1, 2));

        botonCerrarSesion.setText("Cerrar sesión");
        botonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarSesionActionPerformed(evt);
            }
        });
        PanelInferior.add(botonCerrarSesion);

        detallesPunto.setColumns(20);
        detallesPunto.setRows(5);
        scrollDetallesPunto.setViewportView(detallesPunto);

        PanelInferior.add(scrollDetallesPunto);

        getContentPane().add(PanelInferior);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVerVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerVehiculosActionPerformed
        controlador.solicitarVerVehiculos();
    }//GEN-LAST:event_botonVerVehiculosActionPerformed

    
    private void listaVehiculosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaVehiculosValueChanged
        
        if(!evt.getValueIsAdjusting()){
            JList list = (JList) evt.getSource();
            int indiceSeleccionado = list.getSelectedIndex();
            Object vehiculoSeleccionado = list.getModel().getElementAt(indiceSeleccionado);
            controlador.seleccionarVehiculo(vehiculoSeleccionado.toString());
        }
        //String vehiculoSeleccionado = evt.getSource().toString();
    }//GEN-LAST:event_listaVehiculosValueChanged

    private void listaVehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaVehiculosMouseClicked

    }//GEN-LAST:event_listaVehiculosMouseClicked

    private void botonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarSesionActionPerformed
        controlador.cerrarSesion();
    }//GEN-LAST:event_botonCerrarSesionActionPerformed

    
    
    public void mostrarVehiculos(List <String> listaVehiculosConsultados){
        Vector<String> vehiculosMostrados = new Vector<>(listaVehiculosConsultados);
        
        listaVehiculos = new JList<>(vehiculosMostrados);
        scrollListaVehiculos.setViewportView(listaVehiculos);
        
        listaVehiculos.addListSelectionListener((javax.swing.event.ListSelectionEvent evt) -> {
            listaVehiculosValueChanged(evt);
        });
    }
    
    public void errorListaVehiculos(String msg){
        Vector<String> msgError = new Vector<>();
        
        msgError.add(msg);
        listaVehiculos = new JList<>(msgError);
    }
    
    
    public void mostrarDatosPunto(String datosPunto){
        detallesPunto.setText(datosPunto);
    }
    
    
    
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelInferior;
    private javax.swing.JPanel PanelSuperior;
    private javax.swing.JButton botonCerrarSesion;
    private javax.swing.JButton botonVerVehiculos;
    private javax.swing.JTextArea detallesPunto;
    private javax.swing.JList<String> listaVehiculos;
    private javax.swing.JScrollPane scrollDetallesPunto;
    private javax.swing.JScrollPane scrollListaVehiculos;
    // End of variables declaration//GEN-END:variables

   
}
