/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pares_vista_control.atencion;

import javax.swing.JOptionPane;

/**
 *
 * @author g01
 */
public class AtencionClienteVista extends javax.swing.JFrame {

    private final CtrlVistaAtencionCliente controlador;
    
    /**
     * Creates new form FuncionalidadesVista
     */
    public AtencionClienteVista() {
        initComponents();
        controlador = new CtrlVistaAtencionCliente(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonCrearAlquiler = new javax.swing.JButton();
        botonConsultarReservasDia = new javax.swing.JButton();
        botonRegistrarDevolucionVehiculo = new javax.swing.JButton();
        botonMostrarFacturasAlquiler = new javax.swing.JButton();
        botonCrearFacturaIncidencias = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonCrearAlquiler.setText("Crear Alquiler");
        botonCrearAlquiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearAlquilerActionPerformed(evt);
            }
        });

        botonConsultarReservasDia.setText("Consultar Reservas Dia");
        botonConsultarReservasDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarReservasDiaActionPerformed(evt);
            }
        });

        botonRegistrarDevolucionVehiculo.setText("Registrar Devolucion");
        botonRegistrarDevolucionVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarDevolucionVehiculoActionPerformed(evt);
            }
        });

        botonMostrarFacturasAlquiler.setText("Mostrar Facturas Alquiler");
        botonMostrarFacturasAlquiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarFacturasAlquilerActionPerformed(evt);
            }
        });

        botonCrearFacturaIncidencias.setText("Crear Factura Incidencias");
        botonCrearFacturaIncidencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearFacturaIncidenciasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonMostrarFacturasAlquiler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonCrearFacturaIncidencias, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonCrearAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonConsultarReservasDia, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonRegistrarDevolucionVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonConsultarReservasDia, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(botonRegistrarDevolucionVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonCrearAlquiler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonCrearFacturaIncidencias, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                    .addComponent(botonMostrarFacturasAlquiler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCrearAlquilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearAlquilerActionPerformed
        // TODO add your handling code here:
        controlador.cambiarVistaCrearAlquiler();
    }//GEN-LAST:event_botonCrearAlquilerActionPerformed

    private void botonConsultarReservasDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarReservasDiaActionPerformed
        // TODO add your handling code here:
        controlador.cambiarVistaConsultarReservasDia();
    }//GEN-LAST:event_botonConsultarReservasDiaActionPerformed

    private void botonRegistrarDevolucionVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarDevolucionVehiculoActionPerformed
        // TODO add your handling code here:
        controlador.cambiarVistaRegistrarDevolucionVehiculo();   
    }//GEN-LAST:event_botonRegistrarDevolucionVehiculoActionPerformed

    private void botonMostrarFacturasAlquilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarFacturasAlquilerActionPerformed
        // TODO add your handling code here:
        controlador.cambiarVistaMostrarFacturas();
    }//GEN-LAST:event_botonMostrarFacturasAlquilerActionPerformed

    private void botonCrearFacturaIncidenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearFacturaIncidenciasActionPerformed
        // TODO add your handling code here:
        controlador.cambiarVistaCrearfacturaIncidencias();
    }//GEN-LAST:event_botonCrearFacturaIncidenciasActionPerformed

    public void mostrarPanel(String text){
        JOptionPane.showMessageDialog(null, text);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConsultarReservasDia;
    private javax.swing.JButton botonCrearAlquiler;
    private javax.swing.JButton botonCrearFacturaIncidencias;
    private javax.swing.JButton botonMostrarFacturasAlquiler;
    private javax.swing.JButton botonRegistrarDevolucionVehiculo;
    // End of variables declaration//GEN-END:variables
}
