/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pares_vista_control.atencion;

import javax.swing.JOptionPane;

/**
 *
 * @author g01
 */
public class DevolucionVehiculoVista extends javax.swing.JFrame {
    private final CtrlVistaDevolucionVehiculo controlador;

    
    public DevolucionVehiculoVista() {
        initComponents();
        botonComprobarReserva.setEnabled(false);
        botonConfirmarDevolucion.setEnabled(false);
        botonCancelarDevolucion.setEnabled(false);
        botonIndicencias.setEnabled(false);
        botonContinuarSinIncidencias.setEnabled(false);
        controlador = new CtrlVistaDevolucionVehiculo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelSuperior = new javax.swing.JPanel();
        PanelSuperiorSup = new javax.swing.JPanel();
        etiqCampoIDReserva = new javax.swing.JLabel();
        campoIDReserva = new javax.swing.JTextField();
        botonComprobarReserva = new javax.swing.JButton();
        PanelSuperiorInf = new javax.swing.JPanel();
        scrollDatosReserva = new javax.swing.JScrollPane();
        campoDatosReserva = new javax.swing.JTextArea();
        PanelInferior = new javax.swing.JPanel();
        PaneIInferiorSup = new javax.swing.JPanel();
        botonConfirmarDevolucion = new javax.swing.JButton();
        botonCancelarDevolucion = new javax.swing.JButton();
        PanelInferiorInf = new javax.swing.JPanel();
        botonContinuarSinIncidencias = new javax.swing.JButton();
        botonIndicencias = new javax.swing.JButton();
        botonCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(579, 350));
        getContentPane().setLayout(new java.awt.GridLayout(2, 1));

        PanelSuperior.setLayout(new java.awt.GridLayout(2, 1));

        PanelSuperiorSup.setLayout(new java.awt.GridLayout(1, 3));

        etiqCampoIDReserva.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqCampoIDReserva.setText("Introduzca el ID de la reserva:");
        PanelSuperiorSup.add(etiqCampoIDReserva);

        campoIDReserva.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoIDReservaFocusGained(evt);
            }
        });
        campoIDReserva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoIDReservaKeyTyped(evt);
            }
        });
        PanelSuperiorSup.add(campoIDReserva);

        botonComprobarReserva.setText("Comprobar reserva");
        botonComprobarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonComprobarReservaActionPerformed(evt);
            }
        });
        PanelSuperiorSup.add(botonComprobarReserva);

        PanelSuperior.add(PanelSuperiorSup);

        PanelSuperiorInf.setLayout(new java.awt.GridLayout(1, 1));

        campoDatosReserva.setColumns(20);
        campoDatosReserva.setRows(5);
        scrollDatosReserva.setViewportView(campoDatosReserva);

        PanelSuperiorInf.add(scrollDatosReserva);

        PanelSuperior.add(PanelSuperiorInf);

        getContentPane().add(PanelSuperior);

        PanelInferior.setLayout(new java.awt.GridLayout(2, 1));

        PaneIInferiorSup.setLayout(new java.awt.GridLayout(1, 2));

        botonConfirmarDevolucion.setText("Confirmar devolución");
        botonConfirmarDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConfirmarDevolucionActionPerformed(evt);
            }
        });
        PaneIInferiorSup.add(botonConfirmarDevolucion);

        botonCancelarDevolucion.setText("Cancelar devolución");
        botonCancelarDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarDevolucionActionPerformed(evt);
            }
        });
        PaneIInferiorSup.add(botonCancelarDevolucion);

        PanelInferior.add(PaneIInferiorSup);

        PanelInferiorInf.setLayout(new java.awt.GridLayout(1, 3));

        botonContinuarSinIncidencias.setText("Continuar");
        botonContinuarSinIncidencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonContinuarSinIncidenciasActionPerformed(evt);
            }
        });
        PanelInferiorInf.add(botonContinuarSinIncidencias);

        botonIndicencias.setText("Añadir incidencias");
        botonIndicencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIndicenciasActionPerformed(evt);
            }
        });
        PanelInferiorInf.add(botonIndicencias);

        botonCerrarSesion.setText("Cerrar sesión");
        botonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarSesionActionPerformed(evt);
            }
        });
        PanelInferiorInf.add(botonCerrarSesion);

        PanelInferior.add(PanelInferiorInf);

        getContentPane().add(PanelInferior);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void botonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarSesionActionPerformed
        controlador.cerrarSesion();
    }//GEN-LAST:event_botonCerrarSesionActionPerformed

    private void botonComprobarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonComprobarReservaActionPerformed
        controlador.comprobarReserva();
    }//GEN-LAST:event_botonComprobarReservaActionPerformed

    private void campoIDReservaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoIDReservaFocusGained
        campoIDReserva.setText("");
    }//GEN-LAST:event_campoIDReservaFocusGained

    private void campoIDReservaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoIDReservaKeyTyped
        botonComprobarReserva.setEnabled(true);
    }//GEN-LAST:event_campoIDReservaKeyTyped

    private void botonConfirmarDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConfirmarDevolucionActionPerformed
        controlador.confirmarDevolucion();
    }//GEN-LAST:event_botonConfirmarDevolucionActionPerformed

    private void botonCancelarDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarDevolucionActionPerformed
        controlador.cancelarDevolucion();
    }//GEN-LAST:event_botonCancelarDevolucionActionPerformed

    private void botonContinuarSinIncidenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonContinuarSinIncidenciasActionPerformed
        controlador.continuarSinIncidencias();
    }//GEN-LAST:event_botonContinuarSinIncidenciasActionPerformed

    private void botonIndicenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIndicenciasActionPerformed
        controlador.agregarIncidencias();
    }//GEN-LAST:event_botonIndicenciasActionPerformed

    
    public void mostrarPanel(String text){
        JOptionPane.showMessageDialog(null, text);
    }
    
    public void errorReservaInexistente() {
        JOptionPane.showMessageDialog(null, "El id de la reserva es incorrecto o el punto de entrega no es el estipulado.",
                "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    public void errorReservaNoEnAlquiler() {
        JOptionPane.showMessageDialog(null, "La reserva especificada no se encuentra en alquiler en este momento.",
                "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    public void reservaEncontrada(String datosReserva) {
        // Activamos los botones relacionados con la confirmación y mostramos por pantalla
        // los datos de la reserva.
        botonConfirmarDevolucion.setEnabled(true);
        botonCancelarDevolucion.setEnabled(true);
        
        campoDatosReserva.setText(datosReserva+"\n\n¿Quiere seguir adelante con la devolución?");
    }
    
    public void entregaCreadaExitosamente() {
        JOptionPane.showMessageDialog(null, "Se ha registrado la entrega de forma exitosa.");
        
        botonComprobarReserva.setEnabled(false);
        botonConfirmarDevolucion.setEnabled(false);
        botonCancelarDevolucion.setEnabled(false);
        
        botonContinuarSinIncidencias.setEnabled(true);
        botonIndicencias.setEnabled(true);
        campoDatosReserva.setText("¿Desea añadir alguna incidencia?");
    }

    public void errorCreacionEntrega() {
        JOptionPane.showMessageDialog(null, "No se ha logrado registrar la entrega.",
                "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    public void devolucionCancelada() {
        botonComprobarReserva.setEnabled(true);
        botonConfirmarDevolucion.setEnabled(false);
        botonCancelarDevolucion.setEnabled(false);
        
        campoDatosReserva.setText("");
    }
    
    public void registroFinalExitoso() {
        JOptionPane.showMessageDialog(null, "Se han actualizado todos los datos de forma exitosa.");
        
        botonComprobarReserva.setEnabled(false);
        botonConfirmarDevolucion.setEnabled(false);
        botonCancelarDevolucion.setEnabled(false);
        botonContinuarSinIncidencias.setEnabled(false);
        botonIndicencias.setEnabled(false);
        
        campoDatosReserva.setText("");
    }
    
    public void errorRegistroFinal() {
        JOptionPane.showMessageDialog(null, "Ha ocurrido un error en la actualización de los datos.",
                "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    public void errorDevolucionEnCurso() {
        JOptionPane.showMessageDialog(null, "Hay una devolución en curso.",
                "Error", JOptionPane.ERROR_MESSAGE);    
    }
    
    public String obtenerIdReserva() {
        return campoIDReserva.getText();
    }
    
    
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PaneIInferiorSup;
    private javax.swing.JPanel PanelInferior;
    private javax.swing.JPanel PanelInferiorInf;
    private javax.swing.JPanel PanelSuperior;
    private javax.swing.JPanel PanelSuperiorInf;
    private javax.swing.JPanel PanelSuperiorSup;
    private javax.swing.JButton botonCancelarDevolucion;
    private javax.swing.JButton botonCerrarSesion;
    private javax.swing.JButton botonComprobarReserva;
    private javax.swing.JButton botonConfirmarDevolucion;
    private javax.swing.JButton botonContinuarSinIncidencias;
    private javax.swing.JButton botonIndicencias;
    private javax.swing.JTextArea campoDatosReserva;
    private javax.swing.JTextField campoIDReserva;
    private javax.swing.JLabel etiqCampoIDReserva;
    private javax.swing.JScrollPane scrollDatosReserva;
    // End of variables declaration//GEN-END:variables

    

    

    
}
