/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pares_vista_control.atencion;

import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author g01
 */
public class IncidenciasVista extends javax.swing.JFrame {
    private final CtrlVistaIncidencias controlador;

    
    public IncidenciasVista(int idEntrega) {
        initComponents();
        
        campoDescripcionIncidencia.setText("");
        botonNuevaIncidencia.setEnabled(false);
        botonFinalizar.setEnabled(false);
        
        controlador = new CtrlVistaIncidencias(this, idEntrega);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelSuperior = new javax.swing.JPanel();
        PanelSuperiorSup = new javax.swing.JPanel();
        etiqTipoIncidencia = new javax.swing.JLabel();
        selectorTipoIncidencia = new javax.swing.JComboBox<>();
        PanelSuperiorInf = new javax.swing.JPanel();
        etiqDescripcionIncidencia = new javax.swing.JLabel();
        campoDescripcionIncidencia = new javax.swing.JTextField();
        PanelInferior = new javax.swing.JPanel();
        PanelInferiorSup = new javax.swing.JPanel();
        botonCrearIncidencia = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoDatosIncidencia = new javax.swing.JTextArea();
        PanelInferiorInf = new javax.swing.JPanel();
        botonNuevaIncidencia = new javax.swing.JButton();
        botonFinalizar = new javax.swing.JButton();
        botonCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(579, 350));
        getContentPane().setLayout(new java.awt.GridLayout(2, 1));

        PanelSuperior.setLayout(new java.awt.GridLayout(2, 1));

        PanelSuperiorSup.setLayout(new java.awt.GridLayout(1, 3));

        etiqTipoIncidencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqTipoIncidencia.setText("Seleccione el tipo de incidencia:");
        PanelSuperiorSup.add(etiqTipoIncidencia);

        selectorTipoIncidencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Ninguno -", "Accidente", "Avería", "Suciedad extrema", "Retraso en la entrega" }));
        selectorTipoIncidencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectorTipoIncidenciaActionPerformed(evt);
            }
        });
        PanelSuperiorSup.add(selectorTipoIncidencia);

        PanelSuperior.add(PanelSuperiorSup);

        PanelSuperiorInf.setLayout(new java.awt.GridLayout(1, 1));

        etiqDescripcionIncidencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqDescripcionIncidencia.setText("Descripción de la incidencia:");
        PanelSuperiorInf.add(etiqDescripcionIncidencia);
        PanelSuperiorInf.add(campoDescripcionIncidencia);

        PanelSuperior.add(PanelSuperiorInf);

        getContentPane().add(PanelSuperior);

        PanelInferior.setLayout(new java.awt.GridLayout(2, 1));

        PanelInferiorSup.setLayout(new java.awt.GridLayout(1, 2));

        botonCrearIncidencia.setText("Continuar sin cargos extra");
        botonCrearIncidencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearIncidenciaActionPerformed(evt);
            }
        });
        PanelInferiorSup.add(botonCrearIncidencia);

        campoDatosIncidencia.setColumns(20);
        campoDatosIncidencia.setRows(5);
        jScrollPane1.setViewportView(campoDatosIncidencia);

        PanelInferiorSup.add(jScrollPane1);

        PanelInferior.add(PanelInferiorSup);

        PanelInferiorInf.setLayout(new java.awt.GridLayout(1, 3));

        botonNuevaIncidencia.setText("Nueva incidencia");
        botonNuevaIncidencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevaIncidenciaActionPerformed(evt);
            }
        });
        PanelInferiorInf.add(botonNuevaIncidencia);

        botonFinalizar.setText("Finalizar");
        botonFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFinalizarActionPerformed(evt);
            }
        });
        PanelInferiorInf.add(botonFinalizar);

        botonCerrarSesion.setText("Cerrar sesión");
        botonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarSesionActionPerformed(evt);
            }
        });
        PanelInferiorInf.add(botonCerrarSesion);

        PanelInferior.add(PanelInferiorInf);

        getContentPane().add(PanelInferior);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void botonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarSesionActionPerformed
        controlador.cerrarSesion();
    }//GEN-LAST:event_botonCerrarSesionActionPerformed

    private void selectorTipoIncidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectorTipoIncidenciaActionPerformed
        controlador.tipoIncidenciaSeleccionada();
    }//GEN-LAST:event_selectorTipoIncidenciaActionPerformed

    private void botonCrearIncidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearIncidenciaActionPerformed
        controlador.agregarIncidencia();
    }//GEN-LAST:event_botonCrearIncidenciaActionPerformed

    private void botonNuevaIncidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevaIncidenciaActionPerformed
        botonCrearIncidencia.setEnabled(true);
        botonNuevaIncidencia.setEnabled(false);
        botonFinalizar.setEnabled(false);
        campoDatosIncidencia.setText("");
        selectorTipoIncidencia.setSelectedIndex(0);
    }//GEN-LAST:event_botonNuevaIncidenciaActionPerformed

    private void botonFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFinalizarActionPerformed
        controlador.finalizarIncidencias();
    }//GEN-LAST:event_botonFinalizarActionPerformed

    
    public void faltaTipoIncidencia() {
        JOptionPane.showMessageDialog(null, "No se ha seleccionado un tipo de incidencia.",
                "Error", JOptionPane.ERROR_MESSAGE);
    }

    public void faltaDescripcionIncidencia() {
        JOptionPane.showMessageDialog(null, "No se ha añadido una descripción de la incidencia.",
                "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    public void mostrarIncidencias(String datosIncidencias) {
        campoDatosIncidencia.setText(datosIncidencias);
        
        campoDescripcionIncidencia.setText("");
        botonCrearIncidencia.setEnabled(false);
        botonNuevaIncidencia.setEnabled(true);
        botonFinalizar.setEnabled(true);
    }
    
    public String getTipoIncidencia() {
        return String.valueOf(selectorTipoIncidencia.getSelectedItem());
    }
    
    public String getDescripcionIncidencia() {
        return campoDescripcionIncidencia.getText();
    }
      
    
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelInferior;
    private javax.swing.JPanel PanelInferiorInf;
    private javax.swing.JPanel PanelInferiorSup;
    private javax.swing.JPanel PanelSuperior;
    private javax.swing.JPanel PanelSuperiorInf;
    private javax.swing.JPanel PanelSuperiorSup;
    private javax.swing.JButton botonCerrarSesion;
    private javax.swing.JButton botonCrearIncidencia;
    private javax.swing.JButton botonFinalizar;
    private javax.swing.JButton botonNuevaIncidencia;
    private javax.swing.JTextArea campoDatosIncidencia;
    private javax.swing.JTextField campoDescripcionIncidencia;
    private javax.swing.JLabel etiqDescripcionIncidencia;
    private javax.swing.JLabel etiqTipoIncidencia;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> selectorTipoIncidencia;
    // End of variables declaration//GEN-END:variables

}
